# Generated by Django 4.2.4 on 2023-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictioninfo",
            name="knn_variation",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
