# Generated by Django 4.2.4 on 2023-08-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithm", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instance",
            new_name="PlantingInstance",
        ),
    ]
