# Generated by Django 4.2.4 on 2024-06-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_predictioninfo_knn_variation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormattedVariationKNN',
        ),
    ]
