# Generated by Django 4.2.4 on 2023-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithm", "0002_rename_instance_plantinginstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingparameters",
            name="n",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plantingparameters",
            name="humidity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plantingparameters",
            name="k",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plantingparameters",
            name="p",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plantingparameters",
            name="ph",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plantingparameters",
            name="rainfall",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="plantingparameters",
            name="temperature",
            field=models.FloatField(default=0),
        ),
    ]
