# Generated by Django 4.2.4 on 2023-09-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algorithm", "0003_plantingparameters_n_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.IntegerField()),
                ("prediction", models.CharField(max_length=100)),
                ("max_confidence", models.FloatField()),
                ("algorithm_name", models.CharField(max_length=100)),
                ("accuracy", models.FloatField()),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithm.plantinginstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormattedVariationKNN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation", models.CharField(max_length=100)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithm.plantinginstance",
                    ),
                ),
            ],
        ),
    ]
